/**
 * Chhattisgarh Major Industrial Hotspots, Thermal Power Plants & Heavy Metallurgy Hubs.
 * Used for production GIS overlay on the Chhattisgarh spatial air intelligence map.
 */

export interface IndustrialHotspot {
  id: string;
  name: string;
  hindiName: string;
  type: "thermal_power" | "steel_plant" | "aluminum_smelter" | "sponge_iron" | "cement_clinker" | "coal_mine";
  categoryLabel: string;
  district: string;
  lat: number;
  lon: number;
  capacity: string;
  operator: string;
  primaryFuel: string;
  emissionProfile: string;
  icon: string;
  color: [number, number, number];
}

export const CG_INDUSTRIAL_HOTSPOTS: IndustrialHotspot[] = [
  {
    id: "ntpc-korba",
    name: "NTPC Korba Super Thermal Power Station",
    hindiName: "एनटीपीसी कोरबा सुपर थर्मल पावर स्टेशन",
    type: "thermal_power",
    categoryLabel: "Super Thermal Power Plant",
    district: "Korba",
    lat: 22.3854,
    lon: 82.6821,
    capacity: "2,600 MW (4x200 MW + 3x500 MW)",
    operator: "NTPC Limited (Govt of India)",
    primaryFuel: "Bituminous / Sub-bituminous Coal (Gevra & Kusmunda Mines)",
    emissionProfile: "High SO2, NOx, Fly Ash particulate loading",
    icon: "⚡",
    color: [239, 68, 68], // Red
  },
  {
    id: "cseb-hasdeo",
    name: "Hasdeo Thermal Power Station (CSEB/CSPGCL)",
    hindiName: "हसदेव ताप विद्युत गृह (सीएसपीजीसीएल)",
    type: "thermal_power",
    categoryLabel: "State Thermal Power Station",
    district: "Korba",
    lat: 22.3705,
    lon: 82.7202,
    capacity: "1,340 MW (4x210 MW + 1x500 MW)",
    operator: "CSPGCL (Chhattisgarh State Power Generation Co.)",
    primaryFuel: "Coal (SECL Korba Basin)",
    emissionProfile: "High PM2.5 / PM10 point source emission",
    icon: "⚡",
    color: [249, 115, 22], // Orange
  },
  {
    id: "balco-smelter-cpp",
    name: "BALCO Aluminum Smelter & Captive Power Plant",
    hindiName: "बाल्को एल्युमीनियम स्मेल्टर व कैप्टिव पावर प्लांट",
    type: "aluminum_smelter",
    categoryLabel: "Aluminum Smelting Complex",
    district: "Korba",
    lat: 22.4042,
    lon: 82.7483,
    capacity: "570,000 TPA Smelter + 1,710 MW CPP",
    operator: "Vedanta Resources / BALCO",
    primaryFuel: "Captive Coal + Bauxite calcination",
    emissionProfile: "Fluorides, SO2, Coal Ash & Carbon dust",
    icon: "🏭",
    color: [234, 88, 12],
  },
  {
    id: "lanco-amarkantak",
    name: "LANCO Amarkantak Thermal Power Plant",
    hindiName: "लैंको अमरकंटक थर्मल पावर प्लांट",
    type: "thermal_power",
    categoryLabel: "Thermal Power Station",
    district: "Korba",
    lat: 22.3168,
    lon: 82.8594,
    capacity: "600 MW + 1,320 MW exp",
    operator: "LANCO Infratech",
    primaryFuel: "Coal",
    emissionProfile: "SO2 and particulate combustion plume",
    icon: "⚡",
    color: [239, 68, 68],
  },
  {
    id: "bhilai-steel-plant",
    name: "Bhilai Steel Plant (SAIL)",
    hindiName: "भिलाई इस्पात संयंत्र (सेल)",
    type: "steel_plant",
    categoryLabel: "Integrated Steel Complex",
    district: "Durg",
    lat: 21.1824,
    lon: 81.3922,
    capacity: "7.0 Million Tonnes Cr. Steel / Year",
    operator: "Steel Authority of India Ltd. (SAIL)",
    primaryFuel: "Coking Coal, Sintering Gas, Blast Furnace Gas",
    emissionProfile: "Blast furnace emissions, Sinter plant dust, Coke oven gas",
    icon: "🏗️",
    color: [225, 29, 72], // Rose Red
  },
  {
    id: "jindal-steel-raigarh",
    name: "Jindal Steel & Power (JSPL Raigarh)",
    hindiName: "जिंदल स्टील एंड पावर (जेएसपीएल रायगढ़)",
    type: "steel_plant",
    categoryLabel: "Integrated Steel & Power Hub",
    district: "Raigarh",
    lat: 21.9284,
    lon: 83.3768,
    capacity: "3.6 MTPA Steel + 1,000 MW CPP",
    operator: "Jindal Steel & Power Ltd.",
    primaryFuel: "Non-coking coal + Iron ore sponge iron",
    emissionProfile: "Heavy Sponge Iron kiln particulates, fugitive dust, SO2",
    icon: "🏭",
    color: [225, 29, 72],
  },
  {
    id: "ksk-mahanadi",
    name: "KSK Mahanadi Super Thermal Power Project",
    hindiName: "केएसके महानदी सुपर थर्मल पावर प्लांट",
    type: "thermal_power",
    categoryLabel: "Super Thermal Power Plant",
    district: "Janjgir-Champa",
    lat: 21.9421,
    lon: 82.6845,
    capacity: "3,600 MW (6x600 MW)",
    operator: "KSK Energy Ventures / Adani Power",
    primaryFuel: "Coal (Gare Palma / SECL)",
    emissionProfile: "High volume flue gas SO2 / NOx dispersion plume",
    icon: "⚡",
    color: [239, 68, 68],
  },
  {
    id: "db-power-janjgir",
    name: "DB Power Thermal Plant (Baradarha)",
    hindiName: "डीबी पावर थर्मल प्लांट (बाराद्वार)",
    type: "thermal_power",
    categoryLabel: "Thermal Power Station",
    district: "Janjgir-Champa",
    lat: 21.9842,
    lon: 82.9152,
    capacity: "1,200 MW (2x600 MW)",
    operator: "Dainik Bhaskar Group / DB Power",
    primaryFuel: "Coal",
    emissionProfile: "Flue gas combustion particulates & SO2",
    icon: "⚡",
    color: [249, 115, 22],
  },
  {
    id: "gmr-chhattisgarh",
    name: "GMR Chhattisgarh Energy Thermal Station",
    hindiName: "जीएमआर छत्तीसगढ़ एनर्जी थर्मल स्टेशन",
    type: "thermal_power",
    categoryLabel: "Supercritical Thermal Station",
    district: "Raipur",
    lat: 21.3789,
    lon: 81.8214,
    capacity: "1,370 MW (2x685 MW)",
    operator: "Adani Power (formerly GMR)",
    primaryFuel: "Coal (SECL link)",
    emissionProfile: "Combustion flue gas and ash disposal basin",
    icon: "⚡",
    color: [239, 68, 68],
  },
  {
    id: "siltara-industrial-cluster",
    name: "Siltara & Urla Heavy Industrial Belt (Raipur)",
    hindiName: "सिलतरा एवं उरला औद्योगिक प्रक्षेत्र (रायपुर)",
    type: "sponge_iron",
    categoryLabel: "Sponge Iron & Steel Rolling Cluster",
    district: "Raipur",
    lat: 21.3651,
    lon: 81.6542,
    capacity: "100+ Sponge Iron, Induction Furnaces & Rolling Mills",
    operator: "Sarda Energy, Godawari Power, Monnet, Jayaswal Neco",
    primaryFuel: "Coal, Diesel, Heavy Fuel Oil",
    emissionProfile: "Dense fugitive dust, black carbon, kiln flue gas",
    icon: "🏭",
    color: [217, 119, 6],
  },
  {
    id: "ultratech-baloda-bazar",
    name: "UltraTech / Rawan Integrated Cement Complex",
    hindiName: "अल्ट्राटेक रावन सीमेंट संयंत्र",
    type: "cement_clinker",
    categoryLabel: "Cement Clinker & CPP Cluster",
    district: "Baloda Bazar",
    lat: 21.6542,
    lon: 82.0125,
    capacity: "6.5 MTPA Cement + 100 MW CPP",
    operator: "UltraTech Cement / Aditya Birla",
    primaryFuel: "Petcoke, Coal, Limestone Calcination",
    emissionProfile: "Alkaline clinker dust, PM10 stack emissions, NOx",
    icon: "🏢",
    color: [202, 138, 4],
  },
  {
    id: "gevra-coal-mine",
    name: "Gevra & Kusmunda Megamine Complex (SECL)",
    hindiName: "गेवरा व कुसमुंडा ओपनकास्ट कोयला खदान (एसईसीएल)",
    type: "coal_mine",
    categoryLabel: "Asia's Largest Open Cast Coal Mine",
    district: "Korba",
    lat: 22.3421,
    lon: 82.5842,
    capacity: "70+ MTPA Coal Excavation",
    operator: "South Eastern Coalfields Limited (SECL / Coal India)",
    primaryFuel: "Open cast drilling, blasting & heavy haulage",
    emissionProfile: "Massive fugitive dust, particulate PM10, spontaneous coal combustion smoke",
    icon: "⛏️",
    color: [168, 85, 247], // Purple
  },
  {
    id: "chhal-coal-belt",
    name: "Chhal Open Cast Mine & Coal Washery",
    hindiName: "छाल कोयला खदान व वॉशरी",
    type: "coal_mine",
    categoryLabel: "Mand-Raigarh Coal Basin",
    district: "Raigarh",
    lat: 22.1181,
    lon: 83.1406,
    capacity: "12 MTPA Coal extraction & washery",
    operator: "SECL Mand-Raigarh",
    primaryFuel: "Coal transport, conveyor transfer",
    emissionProfile: "Coal dust transport, high localized ambient PM2.5/PM10",
    icon: "⛏️",
    color: [168, 85, 247],
  },
];
