/**
 * Climate data service — reads pre-aggregated JSON files generated by
 * scripts/precompute-climate.mjs from the NASA POWER CSV data (1984-2024).
 *
 * The JSON files live in data/climate/ and are bundled with the Next.js build,
 * so they work on Vercel without needing the large CSV dataset.
 */

import districtSummariesJson from '@/data/climate/district-summaries.json'
import yearlyAveragesJson from '@/data/climate/yearly-averages.json'
import monthlyAveragesJson from '@/data/climate/monthly-averages.json'
import dailyRecentJson from '@/data/climate/daily-recent.json'

export interface DistrictClimate {
  district: string
  division: string
  lat: number
  lon: number
  temperature: number
  rainfall: number
  humidity: number
  ghi: number
}

export interface MonthlyAverage {
  month: string // YYYY-MM or YYYY-MM-DD
  temperature: number
  rainfall: number
  humidity: number
  ghi: number
}

export interface YearlyAverage {
  year: number
  temperature: number
  rainfall: number
  humidity: number
  ghi: number
}

// ── Type the imported JSON ──────────────────────────────────────────────────
const districtSummaries = districtSummariesJson as DistrictClimate[]

interface YearlyRow {
  district: string
  year: number
  temperature: number
  rainfall: number
  humidity: number
  ghi: number
}
const yearlyAverages = yearlyAveragesJson as YearlyRow[]

interface MonthlyRow {
  district: string
  month: string
  temperature: number
  rainfall: number
  humidity: number
  ghi: number
}
const monthlyAverages = monthlyAveragesJson as MonthlyRow[]

interface DailyRow {
  district: string
  date: string
  temperature: number | null
  rainfall: number | null
  humidity: number | null
  ghi: number | null
}
const dailyRecent = dailyRecentJson as DailyRow[]

/**
 * Get the list of all districts with their 2024 averages
 */
export function getDistrictClimateSummaries(): DistrictClimate[] {
  return districtSummaries
}

/**
 * Get monthly averages for a district, optionally constrained to a year range
 */
export function getDistrictMonthlyHistory(
  district: string,
  startYear?: number,
  endYear?: number
): MonthlyAverage[] {
  return monthlyAverages
    .filter((r) => {
      if (r.district !== district) return false
      const year = parseInt(r.month.substring(0, 4))
      if (startYear && year < startYear) return false
      if (endYear && year > endYear) return false
      return true
    })
    .map((r) => ({
      month: r.month,
      temperature: r.temperature,
      rainfall: r.rainfall,
      humidity: r.humidity,
      ghi: r.ghi,
    }))
}

/**
 * Get yearly averages for a district across all years
 */
export function getDistrictYearlyHistory(district: string): YearlyAverage[] {
  return yearlyAverages
    .filter((r) => r.district === district)
    .map((r) => ({
      year: r.year,
      temperature: r.temperature,
      rainfall: r.rainfall,
      humidity: r.humidity,
      ghi: r.ghi,
    }))
}

/**
 * Get all district names
 */
export function getDistrictNames(): string[] {
  return districtSummaries.map((d) => d.district)
}

/**
 * Get recent daily data for a district (last N days of available data)
 */
export function getDistrictRecentDaily(district: string, days: number = 30): MonthlyAverage[] {
  const districtDays = dailyRecent
    .filter((r) => r.district === district)
    .sort((a, b) => b.date.localeCompare(a.date)) // newest first
    .slice(0, days)
    .reverse() // oldest first for chart display

  return districtDays.map((r) => ({
    month: r.date,
    temperature: r.temperature ?? 0,
    rainfall: r.rainfall ?? 0,
    humidity: r.humidity ?? 0,
    ghi: r.ghi ?? 0,
  }))
}
